/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.sdnplatform.sync.thrift;


@SuppressWarnings("all") public class Constants {

  public static final String VERSION = "1.0.0";

}
